apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  storageClassName: ""
  volumeName: database-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.volume.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: {{ .Values.database.volume.id }}
  capacity:
    storage: {{ .Values.database.volume.size }}
  claimRef:
    name: database-pvc
